/aruco_node:
  ros__parameters:
    marker_size: 0.2
    aruco_dictionary_id: DICT_5X5_250
    image_topic: /depth_camera_1/image_raw
    camera_info_topic: /depth_camera_1/camera_info
    camera_frame: camera_1
